### ISSUE TITLE
Definition of "Public" 

### ISSUE THREAD

**Issue by x011** [marcelscruz/public-apis#260]
Many of the so-called public APIs aren't public at all; some of them are restricted and others require pre-approval. What is the definition of "public" being used for this project? I'm raising awareness about this because it's highly misleading to label something as public, which typically implies free usage, when in reality many APIs aren't so.

Please make no mistake that I truly appreciate the effort put into this project, but I fail to see how paid or pre-approved APIs can be considered public.

**Comment by marcelscruz** [comment]
Public means it can be accessed from outside the organization/company/project that created it, sometimes it's paid, sometimes it's free, some require some kind of approval or access key, and some can be accessed straightaway without restrictions.
