### ISSUE TITLE
exchangerate.host updated free tier

### ISSUE THREAD

**Issue by Willsr71** [marcelscruz/public-apis#327]
exchangerate.host has updated their free tier to require an API key and disallow SSL. SSL is now a paid feature apparently.

Pricing link for reference: https://exchangerate.host/product

Also for reference, the response I got using SSL:
```json
{
    "success": false,
    "error": {
        "code": 105,
        "type": "https_access_restricted",
        "info": "Access Restricted - Your current Subscription Plan does not support HTTPS Encryption."
    }
}
```

**Comment by marcelscruz** [comment]
Updated.
