### ISSUE TITLE
Blockchain Explorer' Category in Our Public API Listings

### ISSUE THREAD

**Issue by hello07world** [marcelscruz/public-apis#336]
Hi,
I propose creating a new category titled "Blockchain Explorer." This would not only streamline searches but also enhance the organization of our API listings, making it easier for users to find specific tools tailored to blockchain exploration. I am ready to contribute by adding several publicly available API links that provide direct access to blockchain explorer services.

**Comment by marcelscruz** [comment]
We already have a `Blockchain` category.
How would the one you propose be different from that? Is there a real need to create a separate one?

**Comment by hello07world** [comment]
Yes, I think so because each blockchain can have multiple explorer pages i.e. bitcoin have following websites for explorer! 
https://www.blockchain.com/explorer
https://bitcoinexplorer.org/
https://blockchair.com/bitcoin

This is only for bitcoin, same goes for Ethereum, BSC and Solana. I think it could be a good idea.
