### ISSUE TITLE
Remove or Update FishWatch link

### ISSUE THREAD

**Issue by Gordi90** [marcelscruz/public-apis#359]
The FishWatch link is redirected, and no longer works. If anyone is aware of an up to date link to the API please update.

**Comment by JuanPabloDiaz** [comment]
That is correct @Gordi90,
https://www.fishwatch.gov/developers is redirecting to https://www.fisheries.noaa.gov/topic/sustainable-seafood

**Comment by marcelscruz** [comment]
Removed it, thank you for reporting it.
